### ISSUE TITLE
No Flatpak manifest found in this workspace

### ISSUE THREAD

**Issue by jeffshee** [bilelmoussaoui/flatpak-vscode#187]
Hi,
Thanks for developing the extension. I'm new to Flatpak. (Sorry if this issue is not an issue at all.)

I created a HelloWorld Flatpak by following [Flatpak's documentation](https://docs.flatpak.org/en/latest/first-build.html#create-the-app).
I can build and run the Flatpak by using `flatpak-builder`.
However, I couldn't use the extension to do anything Flatpak-related. 
The extension seems couldn't detect the manifest, which as you can see there is manifest in the workspace.
I even tried with both JSON and YAML, but nothing helped.

![Screenshot from 2022-08-31 20-45-34](https://user-images.githubusercontent.com/25530920/187671295-23e119df-887f-4665-b1d5-f66ab567bc81.png)

(I think we need some documentation for beginners...)

**Comment by SeaDve** [comment]
That may be the checks being too nitpicky, can you paste the manifest here?

**Comment by jeffshee** [comment]
@SeaDve Sure.

JSON
```json
{
    "app-id": "io.jeffshee.Test",
    "runtime": "org.gnome.Platform",
    "runtime-version": "42",
    "sdk": "org.gnome.Sdk",
    "command": "hello.sh",
    "modules": [
      {
        "name": "hello",
        "buildsystem": "simple",
        "build-commands": [
          "install -D hello.sh /app/bin/hello.sh"
        ],
        "sources": [
          {
            "type": "file",
            "path": "hello.sh"
          }
        ]
      }
    ]
  }
```
YAML
```yaml
app-id: io.jeffshee.Test
runtime: org.gnome.Platform
runtime-version: '42'
sdk: org.gnome.Sdk
command: hello.sh
modules:
  - name: hello
    buildsystem: simple
    build-commands:
      - "install -D hello.sh /app/bin/hello.sh"
    sources:
      - type: file
        path: hello.sh
```
